In [2]:
import numpy as np
import os

In [3]:
base_path = "../data"
file_list = os.listdir(base_path)
print("קבצים:", file_list)

קבצים: ['NTU60_CS.npz', 'NTU60_CV.npz']


In [4]:

# טען קובץ ראשון
data = np.load(os.path.join(base_path, file_list[0]), allow_pickle=True)
print("שדות בקובץ:", data.files)

שדות בקובץ: ['x_train', 'y_train', 'x_test', 'y_test']


In [5]:
file_path = os.path.join(base_path, file_list[0])
data = np.load(file_path, allow_pickle=True)
print( data)
print("שדות בקובץ:", data.files)


NpzFile '../data\\NTU60_CS.npz' with keys: x_train, y_train, x_test, y_test
שדות בקובץ: ['x_train', 'y_train', 'x_test', 'y_test']


In [6]:
x_train = data['x_train']
y_train = data['y_train']
x_test = data['x_test']
y_test = data['y_test']
print("x_train:", x_train.shape)
print("y_train:", y_train.shape)

x_train: (40091, 300, 150)
y_train: (40091, 60)


In [7]:
print( y_train)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [7]:
sample= x_train[0]  
print("sample shape:", sample.shape)
print("דגימה:", sample[0])

sample shape: (300, 150)
דגימה: [-0.0142139  -0.2600664   0.07078004  0.          0.          0.
  0.0134507   0.2550613  -0.08086991 -0.0194785   0.3752589  -0.13277197
 -0.12139881  0.1784915   0.00219512 -0.1314542  -0.00399208  0.02782607
 -0.11363    -0.0897713  -0.15822506 -0.115794   -0.11529639 -0.16402602
  0.11258529  0.1413751  -0.12611198  0.1888104  -0.0479089  -0.08698893
 -0.04042931 -0.11375588 -0.17401099 -0.10246171 -0.11562458 -0.17218995
 -0.06956321 -0.25812408  0.06370401 -0.03481771 -0.56871897  0.18961406
  0.01194139 -0.8528631   0.3393798  -0.02829151 -0.9090596   0.3795271
  0.03759418 -0.2648145   0.01523805  0.0782456  -0.5788935   0.103616
  0.11055969 -0.8658776   0.22849107  0.06281899 -0.93439615  0.25412893
  0.01022999  0.1920642  -0.05871201 -0.1123116  -0.13711679 -0.18235803
 -0.13335001 -0.0867022  -0.18722796 -0.14522856 -0.1337747  -0.16857696
 -0.1054839  -0.15126729 -0.16524196  0.          0.          0.
  0.          0.          0.          

In [8]:
import pandas as pd
pd.DataFrame(sample[0].reshape((50, 3)), columns=['x', 'y', 'z']).head()


x         y         z
0 -0.014214 -0.260066  0.070780
1  0.000000  0.000000  0.000000
2  0.013451  0.255061 -0.080870
3 -0.019478  0.375259 -0.132772
4 -0.121399  0.178492  0.002195

In [16]:
frame = x_train[0][0]  # הדוגמה הראשונה, הפריים הראשון
print("פריים:", frame)
plot_skeleton(frame)


פריים: [-0.0142139  -0.2600664   0.07078004  0.          0.          0.
  0.0134507   0.2550613  -0.08086991 -0.0194785   0.3752589  -0.13277197
 -0.12139881  0.1784915   0.00219512 -0.1314542  -0.00399208  0.02782607
 -0.11363    -0.0897713  -0.15822506 -0.115794   -0.11529639 -0.16402602
  0.11258529  0.1413751  -0.12611198  0.1888104  -0.0479089  -0.08698893
 -0.04042931 -0.11375588 -0.17401099 -0.10246171 -0.11562458 -0.17218995
 -0.06956321 -0.25812408  0.06370401 -0.03481771 -0.56871897  0.18961406
  0.01194139 -0.8528631   0.3393798  -0.02829151 -0.9090596   0.3795271
  0.03759418 -0.2648145   0.01523805  0.0782456  -0.5788935   0.103616
  0.11055969 -0.8658776   0.22849107  0.06281899 -0.93439615  0.25412893
  0.01022999  0.1920642  -0.05871201 -0.1123116  -0.13711679 -0.18235803
 -0.13335001 -0.0867022  -0.18722796 -0.14522856 -0.1337747  -0.16857696
 -0.1054839  -0.15126729 -0.16524196  0.          0.          0.
  0.          0.          0.          0.          0.          0

IndexError: invalid index to scalar variable.

In [9]:
frame = sample[0].reshape((50, 3))
print("פריים אחרי reshape:", frame.shape)


פריים אחרי reshape: (50, 3)


In [10]:
print(len(frame))          # כמה נקודות יש
print(frame[0])            # איך נראית נקודה אחת


50
[-0.0142139  -0.2600664   0.07078004]


In [11]:
import sys
import os
sys.path.append(os.path.abspath(".."))

import matplotlib.pyplot as plt
from utils.skeleton_utils import plot_skeleton

In [12]:
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(40091, 60))

In [13]:
i=10
skeleton_sequence = x_train[i]
print("מספר פריימים בתנועה:", skeleton_sequence.shape[0])
print("label =", y_train[i])
print("מספר תנועות ייחודיות:", len(np.unique(y_train[1])))  # אמור להחזיר 60



מספר פריימים בתנועה: 300
label = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
מספר תנועות ייחודיות: 2


In [14]:
# ננגן את השלד לאורך זמן
plt.figure()
for frame in skeleton_sequence:
    plot_skeleton(frame)

IndexError: invalid index to scalar variable.

<Figure size 640x480 with 0 Axes>